# PATHS: change accordingly
data_directory: '/path/to/dataset' # path to wavs and metafile directory
log_directory: '/path/to/logdir'   # weights and logs are stored here
metadata_filename: 'metadata.csv'  # name of metadata file under data_directory
train_metadata_filename: 'train_metafile.txt' # target file for training metadata
valid_metadata_filename: 'valid_metafile.txt'
session_name: melgan                 # session naming, can be specified in command line
data_name: ljspeech

# DATA
n_samples: 100000
n_test: 100
mel_start_value: .5
mel_end_value: -.5

# AUDIO
sampling_rate: 22050
n_fft: 2048
mel_channels: 80
hop_length: 275
win_length: 1100
f_min: 40
f_max: null
normalizer: WaveRNN                 # which mel normalization to use from utils.audio.py  [MelGAN or WaveRNN]
# TOKENIZER
phoneme_language: 'en'
with_stress: False                   # use stress symbols in phonemization