# ARCHITECTURE
transformer_kinds :
    - 'text_text'
#    - 'mel_text'
#    - 'text_mel'
#    - 'mel_mel'
speech_encoder_num_layers : 1
speech_decoder_num_layers : 1
text_encoder_num_layers : 1
text_decoder_num_layers : 1
speech_model_dimension : 256
text_model_dimension : 256
speech_encoder_num_heads : 1
speech_decoder_num_heads : 1
text_encoder_num_heads : 4
text_decoder_num_heads : 4
text_encoder_feed_forward_dimension : 512
text_decoder_feed_forward_dimension : 512
speech_encoder_feed_forward_dimension : 512
speech_decoder_feed_forward_dimension : 512
speech_encoder_prenet_dimension : 256
speech_decoder_prenet_dimension : 256
max_position_encoding : 10000
speech_postnet_conv_filters : 256
speech_postnet_conv_layers : 5
speech_postnet_kernel_size : 5
dropout_rate : 0.1
# DATA
#n_samples : 100000
n_samples : 1000
mel_channels : 80
sr : 22050
mel_start_vec_value : -3
mel_end_vec_value : 1
# TRAINING
use_decoder_prenet_dropout_schedule : True
decoder_prenet_dropout_schedule_max : 0.9
decoder_prenet_dropout_schedule_min : 0.5
decoder_prenet_dropout_schedule_max_steps : 30_000
fixed_decoder_prenet_dropout : 0.5
epochs : 100000
batch_size : 4
learning_rate : 5.0e-5
mask_prob : 0.3
use_block_attention : False
block_attention_schedule:
    - [7, 30_000]
    - [2, 40_000]
debug : False
# LOGGING
text_freq : 2000
image_freq : 1000
weights_save_freq: 1000
plot_attention_freq: 2000
keep_n_weights: 5
# TOKENIZER
tokenizer_alphabet: "\"!,.:;?'-() abcdefghijklmnopqrstuvwxyzäüöß"