# ARCHITECTURE
transformer_kinds:
  - 'text_text'
  - 'mel_text'
  - 'text_mel'
  - 'mel_mel'
speech_encoder_num_layers: 4
speech_decoder_num_layers: 4
text_encoder_num_layers: 4
text_decoder_num_layers: 4
speech_model_dimension: 256
text_model_dimension: 256
speech_encoder_num_heads: 4
speech_decoder_num_heads: 4
text_encoder_num_heads: 4
text_decoder_num_heads: 4
text_encoder_feed_forward_dimension: 512
text_decoder_feed_forward_dimension: 512
speech_encoder_feed_forward_dimension: 512
speech_decoder_feed_forward_dimension: 512
speech_encoder_prenet_dimension: 256
speech_decoder_prenet_dimension: 256
max_position_encoding: 100000
speech_postnet_conv_filters: 256
speech_postnet_conv_layers: 5
speech_postnet_kernel_size: 5
dropout_rate: 0.1
# DATA
n_samples: 100000
mel_channels: 80
sr: 22050
mel_start_vec_value: -3
mel_end_vec_value: 1
# TRAINING
dropout_schedule:
  - [0, 0.9]
  - [60_000. 0.3]
learning_rate_schedule:
  - [0, 1.0e-4]
  - [300_000, 1.0e-4]
  - [600_000, 1.0e-5]
max_steps: 900_000
batch_size: 16
mask_prob: 0.3
debug: False
learning_rate: 1.0e-4 # for initialization
# LOGGING
text_freq: 100_000
image_freq: 50_000
weights_save_freq: 50_000
plot_attention_freq: 1_000
keep_n_weights: 5
keep_checkpoint_every_n_hours: 1
# TOKENIZER
use_phonemes: True
phoneme_language: 'en'
tokenizer_alphabet: "\"!,.:;?'-() abcdefghijklmnopqrstuvwxyzäüöß"